name = "grade-m2"
compatibility_date = "2025-07-15"

# Next.js on Pages 配置
[build]
command = "npm run cf:build"

# 静态资源配置
[assets]
directory = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "grade-m2-db"
database_id = "f34cb71f-7aa0-4907-8d9e-da5444ca0311"

[vars]
NODE_ENV = "production"
